USE [master]
GO

/****** Object:  Database [PERFDB]    Script Date: Do 27.07.2023 17:30:53 ******/
DROP DATABASE [PERFDB]
GO

/****** Object:  Database [PERFDB]    Script Date: Do 27.07.2023 17:30:53 ******/
CREATE DATABASE [PERFDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PERFDB', FILENAME = N'/var/opt/mssql/data/PERFDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PERFDB_log', FILENAME = N'/var/opt/mssql/data/PERFDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PERFDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PERFDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PERFDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PERFDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PERFDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PERFDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PERFDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PERFDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PERFDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PERFDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PERFDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PERFDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PERFDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PERFDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PERFDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PERFDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PERFDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PERFDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PERFDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PERFDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PERFDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PERFDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PERFDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PERFDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PERFDB] SET  MULTI_USER 
GO

ALTER DATABASE [PERFDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PERFDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PERFDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PERFDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PERFDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PERFDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PERFDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [PERFDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PERFDB] SET  READ_WRITE 
GO


USE [master]
GO

/****** Object:  Database [PERFDB]    Script Date: Do 27.07.2023 17:30:53 ******/
DROP DATABASE [PERFDB]
GO

/****** Object:  Database [PERFDB]    Script Date: Do 27.07.2023 17:30:53 ******/
CREATE DATABASE [PERFDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PERFDB', FILENAME = N'/var/opt/mssql/data/PERFDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PERFDB_log', FILENAME = N'/var/opt/mssql/data/PERFDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PERFDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PERFDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PERFDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PERFDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PERFDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PERFDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PERFDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PERFDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PERFDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PERFDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PERFDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PERFDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PERFDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PERFDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PERFDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PERFDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PERFDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PERFDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PERFDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PERFDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PERFDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PERFDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PERFDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PERFDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PERFDB] SET  MULTI_USER 
GO

ALTER DATABASE [PERFDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PERFDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PERFDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PERFDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PERFDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PERFDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PERFDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [PERFDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PERFDB] SET  READ_WRITE 
GO


USE [PERFDB]
GO

/****** Object:  Table [dbo].[TableOne]    Script Date: Do 27.07.2023 17:31:12 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TableOne]') AND type in (N'U'))
DROP TABLE [dbo].[TableOne]
GO

/****** Object:  Table [dbo].[TableOne]    Script Date: Do 27.07.2023 17:31:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TableOne](
	[column_1] [nvarchar](50) NOT NULL,
	[column_2] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO


